/**
 * ScriptPanel — Shows the live R script generated by user actions.
 *
 * This is the reproducibility backbone of PsychR. Every click
 * appends valid R syntax here. Users can copy, edit, and re-run it.
 */

import { usePsychrStore } from '../../store'

export function ScriptPanel() {
  const sessionScript = usePsychrStore((s) => s.sessionScript)
  const clearScript = usePsychrStore((s) => s.clearScript)

  const handleCopy = () => {
    navigator.clipboard.writeText(sessionScript).catch(() => {})
  }

  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center justify-between px-3 py-2.5 border-b border-gray-200 bg-white">
        <div>
          <p className="text-xs font-semibold text-gray-800">R Script</p>
          <p className="text-xs text-gray-400">Auto-generated — fully reproducible</p>
        </div>
        <div className="flex gap-1.5">
          <button
            onClick={handleCopy}
            className="text-xs bg-gray-100 hover:bg-gray-200 text-gray-600 px-2 py-1 rounded transition-colors"
          >
            Copy
          </button>
          <button
            onClick={clearScript}
            className="text-xs bg-gray-100 hover:bg-gray-200 text-gray-600 px-2 py-1 rounded transition-colors"
          >
            Clear
          </button>
        </div>
      </div>
      <pre className="flex-1 overflow-auto p-3 text-xs font-mono text-gray-800 bg-gray-950 text-green-400 leading-relaxed">
        {sessionScript}
      </pre>
    </div>
  )
}
