/**
 * Tab 7: Markdown / Quarto Report Editor
 *
 * A Quarto-flavored markdown editor with live preview.
 * Insert results from the Analyze tab, citations, and plots.
 * Export via Quarto CLI or as HTML preview.
 */

import { useState } from 'react'
import { WorkspaceLayout, PanelHeader } from '../../components/layout/WorkspaceLayout'
import { usePsychrStore } from '../../store'
import { renderMarkdownPreview } from '../../utils/markdown-preview'

const STARTER_TEMPLATE = `---
title: "Research Report"
author: "Your Name"
date: "2026-03-30"
format:
  html:
    toc: true
    theme: default
  pdf:
    documentclass: apa7
---

# Abstract

Write your abstract here.

# Introduction

Introduce your research question and hypotheses.

# Method

## Participants

Describe your sample.

## Measures

Describe your measures.

## Procedure

Describe your procedure.

# Results

Your PsychR results will appear here. Use the **Insert Result** button to add analysis output.

# Discussion

Discuss your findings.

# References

References will be inserted from your Citation Manager.
`

export function MarkdownTab() {
  const markdownContent = usePsychrStore((s) => s.markdownContent)
  const setMarkdownContent = usePsychrStore((s) => s.setMarkdownContent)
  const results = usePsychrStore((s) => s.results)
  const citations = usePsychrStore((s) => s.citations)
  const sessionScript = usePsychrStore((s) => s.sessionScript)

  const [showPreview, setShowPreview] = useState(true)

  const handleLoadTemplate = () => {
    if (markdownContent.trim().length > 50) {
      if (!confirm('Replace current content with the APA manuscript template?')) return
    }
    setMarkdownContent(STARTER_TEMPLATE)
  }

  const handleInsertResult = (resultId: string) => {
    const result = results.find((r) => r.id === resultId)
    if (!result) return
    const insert = `\n\n<!-- PsychR Result: ${result.label} -->\n\`\`\`{r echo=FALSE}\n# ${result.label}\n# Generated by PsychR\n${result.rScript}\n\`\`\`\n\n`
    setMarkdownContent(markdownContent + insert)
  }

  const handleInsertCitation = (citId: string) => {
    const cit = citations.find((c) => c.id === citId)
    if (!cit) return
    const authorLast = cit.authors[0]?.split(',')[0] || 'Author'
    const inText = `(${authorLast}, ${cit.year})`
    // In a real editor, would insert at cursor position
    setMarkdownContent(markdownContent + ` ${inText}`)
  }

  const handleExportScript = () => {
    const blob = new Blob([sessionScript], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = 'psychr_session_script.R'
    a.click()
  }

  return (
    <div className="flex h-full overflow-hidden">
      {/* Toolbar + editor */}
      <div className="flex flex-col flex-1 min-w-0">
        {/* Toolbar */}
        <div className="flex items-center gap-2 px-4 py-2 bg-white border-b border-gray-200 flex-wrap">
          <button
            onClick={handleLoadTemplate}
            className="text-xs bg-gray-100 hover:bg-gray-200 text-gray-700 px-2.5 py-1 rounded"
          >
            APA Template
          </button>
          <div className="w-px h-4 bg-gray-300" />
          <select
            onChange={(e) => e.target.value && handleInsertResult(e.target.value)}
            defaultValue=""
            className="text-xs border border-gray-300 rounded px-2 py-1 focus:outline-none"
          >
            <option value="">Insert Result…</option>
            {results.map((r) => (
              <option key={r.id} value={r.id}>{r.label}</option>
            ))}
          </select>
          <select
            onChange={(e) => e.target.value && handleInsertCitation(e.target.value)}
            defaultValue=""
            className="text-xs border border-gray-300 rounded px-2 py-1 focus:outline-none"
          >
            <option value="">Insert Citation…</option>
            {citations.map((c) => (
              <option key={c.id} value={c.id}>
                {c.authors[0]?.split(',')[0]}, {c.year} — {c.title.slice(0, 40)}
              </option>
            ))}
          </select>
          <div className="w-px h-4 bg-gray-300" />
          <button
            onClick={handleExportScript}
            className="text-xs bg-gray-100 hover:bg-gray-200 text-gray-700 px-2.5 py-1 rounded"
          >
            Export R Script
          </button>
          <div className="ml-auto flex items-center gap-1 border border-gray-200 rounded">
            <button
              onClick={() => setShowPreview(false)}
              className={`text-xs px-2.5 py-1 rounded-l ${!showPreview ? 'bg-psychr-midblue text-white' : 'text-gray-600 hover:bg-gray-50'}`}
            >
              Edit
            </button>
            <button
              onClick={() => setShowPreview(true)}
              className={`text-xs px-2.5 py-1 rounded-r ${showPreview ? 'bg-psychr-midblue text-white' : 'text-gray-600 hover:bg-gray-50'}`}
            >
              Split
            </button>
          </div>
        </div>

        {/* Editor / Preview split */}
        <div className={`flex flex-1 overflow-hidden ${showPreview ? 'divide-x divide-gray-200' : ''}`}>
          {/* Editor */}
          <textarea
            value={markdownContent}
            onChange={(e) => setMarkdownContent(e.target.value)}
            className="flex-1 min-w-0 p-5 font-mono text-sm text-gray-800 leading-relaxed resize-none focus:outline-none bg-white"
            spellCheck={false}
            placeholder="Start writing your Quarto/Markdown report here…"
          />

          {/* Preview */}
          {showPreview && (
            <div className="flex-1 min-w-0 overflow-y-auto p-8 bg-white">
              <div className="prose prose-sm max-w-none">
                {renderMarkdownPreview(markdownContent)}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Right sidebar */}
      <aside className="w-56 flex-shrink-0 border-l border-gray-200 bg-gray-50 flex flex-col overflow-y-auto">
        <PanelHeader title="Document" />
        <div className="p-3 space-y-3">
          {/* Word count */}
          <div className="bg-white rounded-lg border border-gray-200 p-3">
            <div className="text-center">
              <p className="text-2xl font-bold text-psychr-blue">
                {markdownContent.split(/\s+/).filter((w) => w.length > 0).length}
              </p>
              <p className="text-xs text-gray-500">words</p>
            </div>
          </div>

          {/* Render button */}
          <button
            disabled
            title="Quarto must be installed. Full rendering available in Phase 3."
            className="w-full bg-psychr-blue text-white text-xs font-medium py-2 rounded opacity-50 cursor-not-allowed"
          >
            Render (Quarto) →
          </button>
          <p className="text-xs text-gray-400 text-center">
            Requires Quarto CLI<br />(Phase 3)
          </p>

          <div className="pt-2 border-t border-gray-200">
            <p className="text-xs font-medium text-gray-600 mb-2">In Your Library</p>
            <div className="space-y-1 text-xs text-gray-500">
              <p>📊 {results.length} result{results.length !== 1 ? 's' : ''}</p>
              <p>📚 {citations.length} citation{citations.length !== 1 ? 's' : ''}</p>
            </div>
          </div>
        </div>
      </aside>
    </div>
  )
}
